export const projects = [
  {
    id: '1',
    icon: './assets/rightArrow.png',
    title: 'Web Design',
    desc: 'Tesla Cloned Landing Page',
    img: './assets/slider-tesla.png',
    link: 'https://dejavu-tesla-clone.netlify.app/',
  },
  {
    id: '2',
    icon: './assets/rightArrow.png',
    title: 'Web Design',
    desc: 'Quiz Application',
    img: './assets/slider-quiz.png',
    link: 'https://deji-quiz.netlify.app/',
  },
  {
    id: '3',
    icon: './assets/rightArrow.png',
    title: 'Graphic Design',
    desc: 'Chatting Application',
    img: './assets/slider-chat.png',
    link: 'https://dejavu-chat-app.netlify.app/',
  },
  {
    id: '4',
    icon: './assets/rightArrow.png',
    title: 'Fourth Design',
    desc: 'Todo List',
    img: './assets/slider-todo.png',
    link: 'https://deji-todo-list.netlify.app/',
  },
  {
    id: '5',
    icon: './assets/rightArrow.png',
    title: 'Fifth Design',
    desc: 'Food Menu',
    img: './assets/slider-menu.png',
    link: 'https://dejavu-food-menu.netlify.app/',
  },
];
